name: speed
description: Yet another speed project.
version: 0.0.3
repository: https://github.com/speedphp/dart-speed

environment:
  sdk: ^3.1.1

platforms:
  linux:
  windows:
  macos:
  android:
  ios:
  web:

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
